apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo
type: Opaque
stringData:
  MONGODB_ROOT_PASSWORD: "adminpass"
  MONGODB_DATABASE: "test"
  MONGODB_USERNAME: "appuser"
  MONGODB_PASSWORD: "apppass"
